fill in the DL terms and most of the DB terms
lintool/guide pull request #36
Opened 2021-01-21 18:06 UTC by crystina-z

2021-01-21 18:53 UTC, MXueguang requested changes

2021-01-21 18:53 UTC, MXueguang commented on chinese-technical-terms.md
> +stride | 步长 ｜ 步長 | bù zhǎng
I think it should be ( bù cháng)?

btw, notice the `|` (en keybord) and `|` (zh keybord) are different. make sure you are typing '|' with English keybord layout, other wise there will be error in format.

2021-01-21 18:53 UTC, MXueguang commented on chinese-technical-terms.md
> +(max/min) pooling | (最大/最小) 池化 ｜(最大/ 最小) 池化 | (zuìdà / zuìxiǎo) chí huà
`(最大/最小) 池化 ｜(最大/ 最小) ` same here. use en keybord

2021-01-21 18:53 UTC, MXueguang commented on chinese-technical-terms.md
> +node | 节点 ｜節點 | jiédiǎn
and here

2021-01-21 18:53 UTC, MXueguang commented on chinese-technical-terms.md
> +query plan |
I am not sure, 查询计划？

2021-01-21 22:24 UTC, lintool commented
@crystina-z would you mind tweaking? ;) Thanks!

2021-01-22 17:43 UTC, MXueguang reviewed
The rest of the translations LGTM

2021-01-22 17:43 UTC, MXueguang commented on chinese-technical-terms.md
>  feed (i.e., to feed into a model) | 餵 | 餵 | wèi
sorry I missed this last time
“喂”

2021-01-22 17:46 UTC, crystina-z commented on chinese-technical-terms.md
>  feed (i.e., to feed into a model) | 餵 | 餵 | wèi
oh I was not checking the previous ones, thanks!

2021-01-22 18:15 UTC, MXueguang approved these changes

2021-01-22 18:52 UTC, merged

2021-01-22 18:52 UTC, lintool commented
Thanks @crystina-z and @MXueguang !